apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None # No cluster IP for headless service
  selector:
    job-name: example-job # Match the job name
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 3 # Total number of successful pod completions needed
  parallelism: 3 # Number of pods running in parallel
  completionMode: Indexed # Ensure pods are indexed (0, 1, 2...)
  template:
    spec:
      subdomain: headless-svc # Link pods to the headless service
      restartPolicy: Never # Pods are not restarted on failure
      containers:
      - name: example-workload
        image: bash:latest
        command:
        - bash
        - -c
        - |
          for i in 0 1 2
          do
            gotStatus="-1"
            wantStatus="0"
            while [ $gotStatus -ne $wantStatus ]
            do
              # Try to ping each pod in the Job
              ping -c 1 example-job-${i}.headless-svc > /dev/null 2>&1
              gotStatus=$?
              if [ $gotStatus -ne $wantStatus ]; then
                echo "Failed to ping pod example-job-${i}.headless-svc, retrying in 1 second..."
                sleep 1
              fi
            done
            echo "Successfully pinged pod: example-job-${i}.headless-svc"
          done
