apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None  # Headless service: No load balancer
  selector:
    job-name: example-job  # Match the job name
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 3  # Total number of successful pod completions needed
  parallelism: 3  # Number of pods running in parallel
  completionMode: Indexed  # Ensure pods are indexed (0, 1, 2...)
  template:
    spec:
      subdomain: headless-svc  # Link pods to the headless service
      restartPolicy: Never
      containers:
      - name: example-workload
        image: bash:latest
        command:
        - bash
        - -c
        - |
          # Wait for all pods to be ready before starting pings
          echo "Waiting for other pods to be ready..."
          sleep 5
          # Loop through the pods and ping each other
          for i in 0 1 2
          do
            # Wait until the pod we're trying to ping is reachable
            while ! ping -c 1 example-job-${i}.headless-svc &>/dev/null
            do
              echo "Waiting for pod example-job-${i}.headless-svc to be reachable..."
              sleep 1
            done
            echo "Successfully pinged pod example-job-${i}.headless-svc"
          done
